[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

# [tasks.my-flow]
# dependencies = [
#     "format",
#     "build",
#     "test"
# ]

[tasks.docker-build]
command = "docker"
args = ["build", "-t", "my-github-notification-image:latest", "."]
dependencies = ["format"]

[tasks.docker-tag]
command = "docker"
args = ["tag", "my-github-notification-image:latest", "${ECR_URI}/my-github-notification-image:latest"]
dependencies = ["docker-build"]

[tasks.docker-push]
command = "docker"
args = ["push", "${ECR_URI}/my-github-notification-image:latest"]

[tasks.docker-run]
command = "docker"
args = ["run", "--rm", "--env-file", ".env", "my-github-notification-image:latest"]
dependencies = [
  "docker-build",
  "docker-tag",
]
