name: CI-Rust

on:
  push:
    paths:
      - '**.rs'
      - '**.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 1

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # 0 にすると全履歴を fecth するようになります。

    - name: Install Python
      uses: actions/setup-python@v2
    - name: Restore mtime
      run: python ./git-restore-mtime.py

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
