name: CI-Rust

on:
  push:
    paths:
      - '**.rs'
      - '**.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 1

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # 0 にすると全履歴を fecth するようになります。

    - name: Install Python
      uses: actions/setup-python@v2
    - name: Restore mtime
      run: python ./git-restore-mtime.py

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - uses: actions-rs/cargo@v1
      with:
        command: clippy

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --verbose
